Adding Description heading for Actions
tj-actions/auto-doc pull request #510
Opened 2023-09-13 19:52 UTC by mw-root

## Description 

This PR adds code to pull the `description` field for actions and add it to the docs if defined.

I am not a great go dev, so I have tried to keep these changes in line with the existing code base.

2023-09-14 17:32 UTC, jackton1 commented
Hi, @mw-root If you're curious you can add a new test to this file [cmd/root_test.go](https://github.com/tj-actions/auto-doc/blob/main/cmd/root_test.go).

2023-09-14 18:18 UTC, jackton1 requested changes

2023-09-14 18:18 UTC, jackton1 commented on internal/constants.go
> +// InputAutoDocStart is the start of the input
@mw-root Can you resolve the lint warnings?

2023-09-18 14:59 UTC, mw-root commented
> Hi, @mw-root If you're curious you can add a new test to this file [cmd/root_test.go](https://github.com/tj-actions/auto-doc/blob/main/cmd/root_test.go).

Hi @jackton1 , I added `description` markers to a couple MD files in `test`. 
These tests all seem to hinge on whether or not the tool ran successfully, so I figured adding desc tags would cover that.  Did you want another run with something specific for the action description?

2023-09-19 20:34 UTC, jackton1 approved these changes

2023-09-19 20:34 UTC, merged